export const nodes = [
  {
    id: '0',
    name: '김빨강',
    days: 7,
    attendance: 7,
    absent: 0,
    attendanceRate: '100%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '조퇴',
    day5: '출석',
    day6: '출석',
    day7: '출석',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '1',
    name: '김주황',
    days: 7,
    attendance: 5,
    absent: 2,
    attendanceRate: '42.8%',
    day1: '출석',
    day2: '결석',
    day3: '출석',
    day4: '결석',
    day5: '출석',
    day6: '출석',
    day7: '출석',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '2',
    name: '김노랑',
    days: 7,
    attendance: 7,
    absent: 0,
    attendanceRate: '100%',
    day1: '조퇴',
    day2: '출석',
    day3: '출석',
    day4: '조퇴',
    day5: '출석',
    day6: '출석',
    day7: '출석',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '3',
    name: '김초록',
    days: 7,
    attendance: 5,
    absent: 2,
    attendanceRate: '42.8%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '결석',
    day5: '출석',
    day6: '결석',
    day7: '출석',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '4',
    name: '김파랑',
    days: 7,
    attendance: 5,
    absent: 2,
    attendanceRate: '42.8%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '결석',
    day5: '출석',
    day6: '결석',
    day7: '출석',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '5',
    name: '김남',
    days: 7,
    attendance: 7,
    absent: 0,
    attendanceRate: '100%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '지각',
    day5: '출석',
    day6: '지각',
    day7: '출석',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '6',
    name: '김보라',
    days: 7,
    attendance: 5,
    absent: 2,
    attendanceRate: '42.8%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '결석',
    day5: '출석',
    day6: '결석',
    day7: '조퇴',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '7',
    name: '박빨강',
    days: 7,
    attendance: 7,
    absent: 0,
    attendanceRate: '100%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '지각',
    day5: '출석',
    day6: '지각',
    day7: '출석',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '8',
    name: '박주황',
    days: 7,
    attendance: 7,
    absent: 0,
    attendanceRate: '100%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '출석',
    day5: '출석',
    day6: '지각',
    day7: '지각',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
  {
    id: '9',
    name: '박노랑',
    days: 7,
    attendance: 7,
    absent: 0,
    attendanceRate: '100%',
    day1: '출석',
    day2: '출석',
    day3: '출석',
    day4: '출석',
    day5: '출석',
    day6: '지각',
    day7: '지각',
    day8: '-',
    day9: '-',
    day10: '-',
    _hasContent: false,
  },
]

// export const randomFromInterval = (min, max) => {
//   return Math.floor(Math.random() * (max - min + 1) + min)
// }

// export const lotsOfNodes = [...Array(100000).keys()].map(key => ({
//   cellA: `Cell A${key}: 100`,
//   cellB: `Cell B${key}: 100`,
//   cellC: `Cell C${key}: 100`,
//   cellD: `Cell D${key}: 100`,
//   cellE: `Cell E${key}: 100`,
//   cellF: `Cell F${key}: 100`,
//   cellG: `Cell G${key}: 100`,
//   cellH: `Cell H${key}: 100`,
//   cellI: `Cell I${key}: 100`,
//   cellJ: `Cell J${key}: 100`,
// }))

// const customId = i => node => ({
//   ...node,
//   nodes: node.nodes ? node.nodes.map(customId(i)) : node.nodes,
//   id: `${i}-${node.id}`,
// })

// export const manyNodes = [...Array(1430)]
//   .map((_, i) => nodes.map(customId(i)))
//   .flat()
