interface Category {
  id?: number
  href: string
  iconSrc?: string
  alt: string
  label: string
  resetItems?: string[]
  children?: Category[]
  exposure?: boolean
  isBreadcrumb?: boolean
  isFilter?: boolean
  isWrite?: string
}

const category: Category[] = [
  {
    id: 0,
    href: '/',
    iconSrc: 'ico_home',
    alt: '대시보드',
    label: '대시보드',
    exposure: true,
    isBreadcrumb: false,
    isFilter: false,
    isWrite: '',
    children: [],
  },
  {
    id: 1,
    href: '/consult',
    iconSrc: 'ico_consult',
    alt: '상담관리',
    label: '상담관리',
    resetItems: [
      'consultPage',
      'resetConsultFilterActive',
      'resetConsultFilterSearch',
      'resetConsultFilter',
    ],
    exposure: true,
    children: [
      {
        href: '/',
        alt: '상담 목록',
        label: '상담 목록',
        exposure: true,
        isBreadcrumb: true,
        isFilter: true,
        isWrite: '/consult/write',
      },
      {
        href: '/detail',
        iconSrc: 'ico_consult',
        alt: '상담 상세',
        label: '상담 상세',
        exposure: false,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/write',
        iconSrc: 'ico_consult',
        alt: '상담 등록',
        label: '상담 등록',
        exposure: false,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/registered',
        alt: '등록완료 목록',
        label: '등록완료 목록',
        exposure: true,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/reject',
        alt: '오류/거부 목록',
        label: '오류/거부 목록',
        exposure: true,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
    ],
  },
  {
    id: 2,
    href: '/subjects',
    iconSrc: 'ico_work',
    alt: '과정관리',
    label: '과정관리',
    resetItems: [
      'subjectPage',
      'resetSubjectFilterActive',
      'resetSubjectFilterSearch',
      'resetSubjectFilter',
    ],
    exposure: true,
    isBreadcrumb: true,
    isFilter: true,
    isWrite: '/subjects/write',
    children: [
      {
        href: '/detail',
        iconSrc: 'ico_work',
        alt: '과정 상세',
        label: '과정 상세',
        exposure: false,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/write',
        iconSrc: 'ico_work',
        alt: '과정 등록',
        label: '과정 등록',
        exposure: false,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
    ],
  },
  {
    id: 3,
    href: '/students',
    iconSrc: 'ico_regist',
    alt: '수강생관리',
    label: '수강생관리',
    resetItems: [
      'studentPage',
      'resetStudentFilterActive',
      'resetStudentFilterSearch',
      'resetStudentFilter',
    ],
    exposure: true,
    isBreadcrumb: true,
    isFilter: true,
    isWrite: '/students/write',
    children: [
      {
        href: '/detail',
        iconSrc: 'ico_consult',
        alt: '수강생 상세',
        label: '수강생 상세',
        exposure: false,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/write',
        iconSrc: 'ico_consult',
        alt: '수강생 등록',
        label: '수강생 등록',
        exposure: false,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/edit',
        iconSrc: 'ico_consult',
        alt: '수강생 수정',
        label: '수강생 수정',
        exposure: false,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
    ],
  },
  {
    id: 4,
    href: '/accounting',
    iconSrc: 'ico_accounting',
    alt: '회계관리',
    label: '회계관리',
    exposure: true,
    children: [
      {
        href: '/',
        alt: '결제 내역',
        label: '결제 내역',
        exposure: true,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/request',
        alt: '환불 신청 내역',
        label: '환불 신청 내역',
        exposure: true,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/refund',
        alt: '환불 완료 내역',
        label: '환불 완료 내역',
        exposure: true,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
      {
        href: '/sales',
        alt: '매출 내역',
        label: '매출 내역',
        exposure: true,
        isBreadcrumb: true,
        isFilter: false,
        isWrite: '',
      },
    ],
  },
  {
    href: '/member',
    iconSrc: '',
    alt: '',
    label: '프로필',
    exposure: false,
    isBreadcrumb: true,
    isFilter: false,
    isWrite: '',
    children: [],
  },
]

export default category
